# Default values for upp-next-video-mapper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
  isResilient: "false"
replicaCount: 2
image:
  repository: coco/upp-next-video-mapper
  pullPolicy: IfNotPresent
resources:
  requests:
    memory: 90Mi
  limits:
    memory: 256Mi
env:
  APP_NAME: ""
  APP_SYSTEM_CODE: ""
  APP_PORT: ""
  Q_GROUP: ""
  Q_READ_TOPIC: ""
  Q_WRITE_TOPIC: ""
  KAFKA_LAG_TOLERANCE: ""
  LOG_LEVEL: ""
